---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cat-service
  name: cat-service
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cat-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cat-service
  name: cat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      deploymentconfig: cat-service
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        deploymentconfig: cat-service
        app: cat-service
    spec:
      containers:
      - image: registry.ocp4.example.com:5000/sm-workshop/cat-service:latest
        imagePullPolicy: Always
        name: cat-service
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          limits:
            memory: 512Mi
            cpu: 200m
        volumeMounts:
        - name: app-config
          mountPath: /home/jboss/app-config
          readOnly: true
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 10
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 10
        env:
        - name: SPRING_CONFIG_LOCATION
          value: /home/jboss/app-config/
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: TZ
          value: Asia/Shanghai
      volumes:
      - name: app-config
        configMap:
          name: cat-service-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
